---
apiVersion: v1
kind: Namespace
metadata:
  name: openebs
  labels:
    kurl.sh/infra: "true"
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 24h
  url: https://openebs.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs
      version: "3.x"
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: openebs
      interval: 12h
  values:
    localprovisioner:
      enableDeviceClass: false
      enableHostpathClass: true
      basePath: /var/lib/replicated/openebs/local # TODO: template
      hostpathClass:
        name: local
        isDefaultClass: true
